package com.yingwumeijia.baseywmj.constant

/**
 * Created by jamisonline on 2017/6/20.
 */
object Constant {

    val DEFAULT_INT_VALUE = -1
    val DEFAULT_BOOLEAN_VALUE = false

    val KEY_LOGIN_SOURCE = "KEY_LOGIN_SOURCE"
    val KEY_CASE_LIST_SOURCE = "KEY_CASE_LIST_SOURCE"
    val KEY_CASE_DETAIL_ID = "KEY_CASE_DETAIL_ID"
    val KEY_CASE_DETAIL_GO_BACK = "KEY_CASE_DETAIL_GO_BACK"
    val KEY_COMPANY_ID = "KEY_COMPANY_ID"
    val KEY_EMPLOYEE_ID = "KEY_EMPLOYEE_ID"
    val KEY_SERVICE_TYPE_STR = "KEY_SERVICE_TYPE_STR"
    val KEY_SERVICE_TYPE_ID = "KEY_SERVICE_TYPE_ID"
    val KEY_SOURCE_TYPE = "KEY_SOURCE_TYPE"
    val KEY_ID = "KEY_ID"
    val KEY_LIST_PIC = "KEY_LIST_PIC"
    val KEY_LIST_TITLE = "KEY_LIST_TITLE"
    val KEY_LIST_CONTENT = "KEY_LIST_CONTENT"
    val KEY_INDEX = "KEY_INDEX"
    val KEY_CHECK_BEAN = "KEY_CHECK_BEAN"
    val KEY_TITLE = "KEY_TITLE"
    val KEY_URL = "KEY_URL"
    val KEY_HAS_TITLE = "KEY_HAS_TITLE"
    val KEY_AVAILABLE = "KEY_AVAILABLE"
    val KEY_COUPON_CODE = "KEY_COUPON_CODE"
    val KEY_PORTRAIT = "KEY_PORTRAIT"
    val KEY_NIKENAME = "KEY_NIKENAME"
    val KEY_MOB = "KEY_MOB"
    val KEY_USER_TITLE = "KEY_USER_TITLE"
    val KEY_INPUT_TEXT = "KEY_INPUT_TEXT"
    val KEY_INPUT_RESULT = "KEY_INPUT_RESULT"
    val PAY_SUCCESS_KEY = "PAY_SUCCESS_KEY"
    val KEY_SESSION_ID = "KEY_SESSION_ID"
    val KEY_FIRST_OKEN_APP = "KEY_FIRST_OKEN_APP"
    val KEY_FIRST_OKEN_CONVERSATION = "KEY_FIRST_OKEN_CONVERSATION"
    val KEY_SEARCH_TYPE = "KEY_SEARCH_TYPE"

    val REQUEST_CODE_GET_CONTACT_INFO = 10001

}